### ISSUE TITLE
verify_first_choice() enter a letter

### ISSUE THREAD

**Issue by ccp84** [ccp84/go_north#3]
Error occurs when entering a letter instead of a number

Start Game - 1   How to play - 2
 d
Traceback (most recent call last):
  File "run.py", line 119, in <module>
    main()
  File "run.py", line 92, in main
    verify_first_choice()
  File "run.py", line 26, in verify_first_choice
    if int(choice) == 1:
ValueError: invalid literal for int() with base 10: 'd'

**Comment by ccp84** [comment]
Bug resolved 

int conversion removed in code and converted check to strings 
    choice = input("Start Game - 1   How to play - 2\n ")
    if choice == '1':
        start_game()
    elif choice == '2':
        display_instructions()
    else:
        print("ERROR please enter 1 or 2")
        verify_first_choice()

output is now as expected
gitpod /workspace/go_north (main) $ python3 run.py
Title screen function running
What is your name?
 me
Hi me
Start Game - 1   How to play - 2
 2
Game Instructions here
Start Game - 1   How to play - 2
